name: Ingest YAML Files
 
#on:
  #schedule:
    #- cron: '0 0 * * *'  # Schedule to run daily at midnight UTC (adjust as needed)
 
jobs:
  ingest-yaml:
    runs-on: windows-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace with your Python version
      -name: install acryl-datahub
          run:
             python -m pip instal acryl-datahub
 
      - name: Install CLI Tool
        run: |
          # Replace the below command with the installation of your CLI tool
          # Example: Install 'my-tool' CLI tool
          datahub ingest -c https://github.com/puneet664/test_dbt_qw/blob/main/recipe_gls.dhub.yaml
