name: Run Python Script1
 
on:
  push:
    branches:
      - main  # Replace with your branch name
    #paths:
     # - '**.xlsx' # Trigger when an Excel file is pushed
 
jobs:
  run-script:
    runs-on: windows-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace with your Python version
 
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Using GitHub token for authentication
        run: |
      - name: Install pandas
        run: |
          python -m pip install openpyxl
          python -m pip install pandas  # Replace with the correct package name
          python -m pip install requests
          python -m pip install pyyaml
          #run: python -m pip install 
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }} " -o Data Taxonomy_workforce.xlsx -L https://github.com/puneet664/test_dbt_qw/blob/main/Data%20Taxonomy_workforce.xlsx
      - name: Run Python Script
        run: python excel_to_json.py  # Replace with your Python script name
      
      - name: Commit files
        run: |
         git config --local user.email "action@github.com"
         git config --local user.name "GitHub Action"
 
         git add glossary/nested_glossary_test.yml  # Stage the generated file within the existing folder

         git commit -m "Generated YAML from Excel"
         git push origin main
