name: Ingest YAML Files in datahub
on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch (modify as needed)
jobs:
  ingest-yaml:
    runs-on: windows-latest  # Using Ubuntu for a wider range of tools
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace with your Python version
 
      - name: Install acryl-datahub
        run: python -m pip install acryl-datahub  # Replace with the correct package name
 
      - name: Ingest YAML using datahub
        run: datahub ingest -c https://raw.githubusercontent.com/puneet664/test_dbt_qw/main/recipe_gls.dhub.yaml
